[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["chmod +x scripts/build.sh", "./scripts/build.sh"]

[start]
cmd = "node dist/index.js"

[variables]
NODE_ENV = "production"